### ISSUE TITLE
features: proposed behaviours and ideas

### ISSUE THREAD

**Issue by aarnphm** [yetone/avante.nvim#51]
A evergreen list of features and requests:

### features.
- [x] <kbd>[[</kbd> and <kbd>]]</kbd> for jumping code block @aarnphm 
- [x] scrollview on code buffer based on chat window cursor @aarnphm https://github.com/yetone/avante.nvim/issues/23#issuecomment-2293037076
- [x] token streaming #73
- [x] asking for users input env if not set #54
- [x] add support for different behaviour #55
- [x] support custom vendor #74
- [x] Workspace context #76 
- [x] Tool use
- [x] Prompt refactoring using aider's search queries @yetone 

### ui.
- [x] change chat window bottom padding for `vim.o.laststatus=3`'

### bugs.
- [x] #32 (fixes with #62)
- [x] handle stream on closed buffer accordingly #73 
	- UI: #61
	- refactor stream to `plenary.Job`, and update view renderer lifecycle accordingly. 

### qol.
- [x] #121 

cc @yetone for more suggestions and added to this tracking list

**Comment by yuchanns** [comment]
Currently, we need to manually select a block using `v` to interact with. Can we auto-select a block based on the tree-sitter?

**Comment by yetone** [comment]
@yuchanns I use my configuration to leverage treesitter and quickly select a node with the simple `.` key.

https://github.com/yetone/cosmos-nvim/blob/b05a44687cd08a3664c084249ce7128df2ea1a6d/lua/layers/editor/configs.lua#L319

**Comment by aarnphm** [comment]
> Currently, we need to manually select a block using `v` to interact with. Can we auto-select a block based on the tree-sitter context?

I think this should be user config. I would prefer it not to be too invasive.

**Comment by yuchanns** [comment]
That's great!

**Comment by wongsingfo** [comment]
> Currently, we need to manually select a block using `v` to interact with. Can we auto-select a block based on the tree-sitter context?

We can use the [incremental_selection feature](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#incremental-selection) provided by nvim-treesitter to quickly select a block.

**Comment by trashhalo** [comment]
New AI editor features dropping in zed. Sharing 🧵 for inspiration 

https://x.com/zeddotdev/status/1825967812629631034?s=61

**Comment by MCodes96** [comment]
@yetone Hey, Supermaven has this feature in VS Code that let's you attach any open files to the chat message.
I'd like to have the possibility to attach files from open buffers to give the AI more context of the setup I'm working on in K8s e.g.

![Bildschirmfoto 2024-09-02 um 14 12 48](https://github.com/user-attachments/assets/d9b069f8-06ea-434a-b209-946d0b755076)

**Comment by olliezhu** [comment]
would it be possible to add support for Nvchad? my understanding is that lazy.vim is currently recommended.

**Comment by aarnphm** [comment]
any plugins manager listed on readme is supported.

**Comment by olliezhu** [comment]
> Check the avante readme and the NVChad docs on how to add plugins.

will do, thanks!

**Comment by zeroaddresss** [comment]
Vertex AI allows to use a set of LLMs (including Claude Sonnet), was wondering if it's possible to integrate Vertex within avante

**Comment by evanrichards** [comment]
> Hey, Supermaven has this feature in VS Code that lets you attach any open files to the chat message.
I'd like to have the possibility to attach files from open buffers to give the AI more context of the setup I'm working on in K8s e.g.

cursor seems to support this with @'ing a file in the prompt.

**Comment by aarnphm** [comment]
> > Hey, Supermaven has this feature in VS Code that lets you attach any open files to the chat message.
> > I'd like to have the possibility to attach files from open buffers to give the AI more context of the setup I'm working on in K8s e.g.
> 
> cursor seems to support this with @'ing a file in the prompt.

you can drag and drop or pasting image at the prompt atm

**Comment by V4G4X** [comment]
Hi, I see that "workspace context" is in the roadmap.

Does that mean if I open nvim with `nvim /path/to/codebase`:
1. Avante will have indexed my entire codebase and pass that as context in the API request?
2. Or will it pass my Neovim workspace (all open buffers) in the API request? 

If it's the first, that's impressive, but can we get 2nd first?  
Or somehow be able to pick which files' context we want to give?

**Comment by aarnphm** [comment]
> Hi, I see that "workspace context" is in the roadmap.
> 
> Does that mean if I open nvim with `nvim /path/to/codebase`:

Check the issue for this.

**Comment by MrZLeo** [comment]
Hi, I am wondering whether auto suggestion feature can be finish by `copilot.lua` itself rather than using copilot API, which cause so many API calls that GitHub even sent a email to warn me about that. 🤣

**Comment by GopherJ** [comment]
I'd suggest to have more lsp features, avante can have an embeded lsp server to assist on diagnostics etc, generate new code actions based on diagnostics

**Comment by GopherJ** [comment]
I just got another idea, avante can maybe provide also OCR features, which should be super cool!

something like: https://github.com/lukas-blecher/LaTeX-OCR

**Comment by aradovic-at-symmetry** [comment]
Bear in mind that there's a more fully-featured analogue for Neovim called [Cline](https://github.com/cline/cline). You may want to repurpose some approaches from it, maybe even parts of the code through an LLM to translate to lua.

**Comment by yuchanns** [comment]
I think this might have some help to do with repo map. (Highlight the [ast-grep](https://github.com/ast-grep/ast-grep))

[Code Quality at Scale with AST Grep and LLMs](https://news.ycombinator.com/item?id=41871661)

**Comment by omerdn1** [comment]
This: https://github.com/yetone/avante.nvim/issues/676

**Comment by BrightXiaoHan** [comment]
Would like to add a feature to automatically generate git commit messages

**Comment by aarnphm** [comment]
> Would like to add a feature to automatically generate git commit messages

I think this is out of scope, but fwiw  you can write this yourself pretty easily.

**Comment by life00** [comment]
Add support for tool (function) calling in gemini models. please.

<https://ai.google.dev/gemini-api/docs/function-calling>

**Comment by JJJHolscher** [comment]
I want to have multiple conversations that I can toggle through for a single project.
The `:AvanteClear` is a good start, but I want to recover past contexts and continue them.

You could add two commands:
- `AvanteOpen name`, which opens the conversation at the corresponding name in the sidebar, or an empty conversation if no such conversation yet exists.
- `AvanteList` which lists all conversation names for the current project.

Optionally you could add
- `AvanteCopy name`, which copies the context currently shown in the sidebar to a new conversation with name `name`.

**Comment by zigotica** [comment]
I created a Telescope picker for providers: https://github.com/yetone/avante.nvim/discussions/1438
Maybe it would be interesting to add it to the core, or at least to the wiki?

**Comment by life00** [comment]
> I created a Telescope picker for providers: [#1438](https://github.com/yetone/avante.nvim/discussions/1438) Maybe it would be interesting to add it to the core, or at least to the wiki?

I think it's already possible, no? `<leader>a?` will open a telescope-like picker to change the provider.

**Comment by zigotica** [comment]
> > I created a Telescope picker for providers: [#1438](https://github.com/yetone/avante.nvim/discussions/1438) Maybe it would be interesting to add it to the core, or at least to the wiki?
> 
> I think it's already possible, no? `<leader>a?` will open a telescope-like picker to change the provider.

wow, didn't know about it, is it documented? 

After checking it out, I am noticing `<leader>a?` doesn't work properly, it shows a list of what, all technically possible models? I mean it shouldn't show models I have not set up. For instance `<leader>a?` will let me choose vercel, but since I have not set it up it will fail. My script handles that.

**Comment by martin-kokos** [comment]
Tool use with Claude apparently works now. Although IMO it should be an opt-in feature due to security considerations.

**Comment by teto** [comment]
you can display the provider with

```
diff --git i/lua/avante/sidebar.lua w/lua/avante/sidebar.lua
index ef48469..56754a8 100644
--- i/lua/avante/sidebar.lua
+++ w/lua/avante/sidebar.lua
@@ -1052,14 +1052,19 @@ function Sidebar:render_input(ask)
   if not Utils.is_valid_container(self.input_container) then return end
 
   local header_text = string.format(
+    -- "HELLO SIR",
+
     "%s%s (" .. Config.mappings.sidebar.switch_windows .. ": switch focus)",
-    Utils.icon("󱜸 "),
+    Config.provider,
+    -- Utils.icon("󱜸 "),
     ask and "Ask" or "Chat with"
   )
 
```

but it wont get updated on change, need to reopen `:AvanteAsk`
